//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MesReservations.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ligne_Reservation
    {
        public int ID_Ligne_Reservation { get; set; }
        public Nullable<System.DateTime> Date_Debut { get; set; }
        public Nullable<System.DateTime> Date_Fin { get; set; }
        public Nullable<bool> Purge { get; set; }
        public int ID_Ressource { get; set; }
        public int ID_Reservation { get; set; }
    
        public virtual Ressource Ressource { get; set; }
        public virtual Reservation Reservation { get; set; }
    }
}
