//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MesReservations.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ressource
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ressource()
        {
            this.Ligne_Reservation = new HashSet<Ligne_Reservation>();
        }
    
        public int ID_Ressource { get; set; }
        public string Nom { get; set; }
        public Nullable<int> Disponibilite { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Date_Achat { get; set; }
        public string QRCode { get; set; }
        public Nullable<bool> Purge { get; set; }
        public int ID_Genre { get; set; }
    
        public virtual Genre Genre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ligne_Reservation> Ligne_Reservation { get; set; }
    }
}
